<30>1 2023-02-17T14:58:00.132117-05:00 giganode1 systemd 1 - - Starting Check PMIE instances are running...
<30>1 2023-02-17T14:58:00.178209-05:00 giganode1 systemd 1 - - Started Check PMIE instances are running.
<30>1 2023-02-17T14:58:00.313149-05:00 giganode1 systemd 1 - - pmie_check.service: Succeeded.
<43>1 2023-02-17T14:58:00.418675-05:00 giganode1 rsyslogd 2018377 - - omfwd: remote server at 192.168.1.85:5140 seems to have closed connection. This often happens when the remote peer (or an interim system like a load balancer or firewall) shuts down or aborts a connection. Rsyslog will re-open the connection if configured to do so (we saw a generic IO Error, which usually goes along with that behaviour). [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<44>1 2023-02-17T14:58:00.418991-05:00 giganode1 rsyslogd 2018377 - - action 'action-7-builtin:omfwd' suspended (module 'builtin:omfwd'), retry 0. There should be messages before this one giving the reason for suspension. [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2007 ]
<43>1 2023-02-17T14:58:00.428220-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<30>1 2023-02-17T14:58:10.132607-05:00 giganode1 systemd 1 - - Starting Check and migrate non-primary pmie farm instances...
<30>1 2023-02-17T14:58:10.177182-05:00 giganode1 systemd 1 - - Started Check and migrate non-primary pmie farm instances.
<30>1 2023-02-17T14:58:10.278388-05:00 giganode1 systemd 1 - - pmie_farm_check.service: Succeeded.
<43>1 2023-02-17T14:58:30.518738-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<43>1 2023-02-17T14:59:00.593785-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<43>1 2023-02-17T14:59:30.707097-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<30>1 2023-02-17T15:00:00.131252-05:00 giganode1 systemd 1 - - Starting system activity accounting tool...
<30>1 2023-02-17T15:00:00.185114-05:00 giganode1 systemd 1 - - sysstat-collect.service: Succeeded.
<30>1 2023-02-17T15:00:00.185255-05:00 giganode1 systemd 1 - - Started system activity accounting tool.
<43>1 2023-02-17T15:00:00.763064-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<43>1 2023-02-17T15:00:30.839355-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<43>1 2023-02-17T15:01:00.879348-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<78>1 2023-02-17T15:01:01.263677-05:00 giganode1 CROND 2120846 - - (root) CMD (run-parts /etc/cron.hourly)
<77>1 2023-02-17T15:01:01.272321-05:00 giganode1 run-parts 2120846 - - (/etc/cron.hourly) starting 0anacron
<77>1 2023-02-17T15:01:01.279378-05:00 giganode1 run-parts 2120846 - - (/etc/cron.hourly) finished 0anacron
<43>1 2023-02-17T15:01:30.919515-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<43>1 2023-02-17T15:02:00.976856-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<43>1 2023-02-17T15:02:31.059115-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<43>1 2023-02-17T15:03:01.100329-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<43>1 2023-02-17T15:03:31.139526-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<43>1 2023-02-17T15:04:01.273486-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<85>1 2023-02-17T15:04:16.352014-05:00 giganode1 sudo 2121088 - -     timp : TTY=pts/0 ; PWD=/home/timp ; USER=root ; COMMAND=/sbin/adduser testguy
<87>1 2023-02-17T15:04:16.355482-05:00 giganode1 sudo 2121088 - - pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
<86>1 2023-02-17T15:04:16.356027-05:00 giganode1 sudo 2121088 - - pam_unix(sudo:session): session opened for user root by timp(uid=0)
<86>1 2023-02-17T15:04:16.458499-05:00 giganode1 useradd 2121089 - - new group: name=testguy, GID=1002
<86>1 2023-02-17T15:04:16.459532-05:00 giganode1 useradd 2121089 - - new user: name=testguy, UID=1001, GID=1002, home=/home/testguy, shell=/bin/bash
<86>1 2023-02-17T15:04:16.904148-05:00 giganode1 sudo 2121088 - - pam_unix(sudo:session): session closed for user root
<85>1 2023-02-17T15:04:22.750369-05:00 giganode1 sudo 2121097 - -     timp : TTY=pts/0 ; PWD=/home/timp ; USER=root ; COMMAND=/bin/passwd testguy testguy
<87>1 2023-02-17T15:04:22.751122-05:00 giganode1 sudo 2121097 - - pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
<86>1 2023-02-17T15:04:22.751318-05:00 giganode1 sudo 2121097 - - pam_unix(sudo:session): session opened for user root by timp(uid=0)
<86>1 2023-02-17T15:04:22.766242-05:00 giganode1 sudo 2121097 - - pam_unix(sudo:session): session closed for user root
<43>1 2023-02-17T15:04:31.378566-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<85>1 2023-02-17T15:04:36.396740-05:00 giganode1 sudo 2121150 - -     timp : TTY=pts/0 ; PWD=/home/timp ; USER=root ; COMMAND=/bin/passwd testguy
<87>1 2023-02-17T15:04:36.401236-05:00 giganode1 sudo 2121150 - - pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
<86>1 2023-02-17T15:04:36.401566-05:00 giganode1 sudo 2121150 - - pam_unix(sudo:session): session opened for user root by timp(uid=0)
<83>1 2023-02-17T15:04:36.404090-05:00 giganode1 passwd 2121151 - - pam_unix(passwd:chauthtok): unrecognized option [yescrypt]
<86>1 2023-02-17T15:04:43.944200-05:00 giganode1 sudo 2121150 - - pam_unix(sudo:session): session closed for user root
<85>1 2023-02-17T15:04:45.193965-05:00 giganode1 sudo 2121158 - -     timp : TTY=pts/0 ; PWD=/home/timp ; USER=root ; COMMAND=/bin/passwd testguy
<87>1 2023-02-17T15:04:45.196281-05:00 giganode1 sudo 2121158 - - pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
<86>1 2023-02-17T15:04:45.197016-05:00 giganode1 sudo 2121158 - - pam_unix(sudo:session): session opened for user root by timp(uid=0)
<83>1 2023-02-17T15:04:45.201600-05:00 giganode1 passwd 2121159 - - pam_unix(passwd:chauthtok): unrecognized option [yescrypt]
<83>1 2023-02-17T15:04:52.474925-05:00 giganode1 passwd 2121159 - - pam_unix(passwd:chauthtok): unrecognized option [yescrypt]
<85>1 2023-02-17T15:04:52.487134-05:00 giganode1 passwd 2121159 - - pam_unix(passwd:chauthtok): password changed for testguy
<86>1 2023-02-17T15:04:52.488199-05:00 giganode1 sudo 2121158 - - pam_unix(sudo:session): session closed for user root
<43>1 2023-02-17T15:05:01.420865-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<29>1 2023-02-17T15:05:03.326286-05:00 giganode1 pcp-pmie 2400 - - Severe demand for real memory 8.3pgsout/s@giganode1.thepushors.com
<86>1 2023-02-17T15:05:12.106024-05:00 giganode1 sshd 2121169 - - Accepted publickey for timp from 192.168.1.85 port 60699 ssh2: RSA SHA256:QaxveQJbYmX1Wmx/p2A7q+CJEZEySEl3Cnk79PVUY2A
<38>1 2023-02-17T15:05:12.112511-05:00 giganode1 systemd-logind 1106 - - New session 60 of user timp.
<30>1 2023-02-17T15:05:12.116578-05:00 giganode1 systemd 1 - - Started Session 60 of user timp.
<86>1 2023-02-17T15:05:12.117537-05:00 giganode1 sshd 2121169 - - pam_unix(sshd:session): session opened for user timp by (uid=0)
<86>1 2023-02-17T15:05:17.326828-05:00 giganode1 sshd 2121176 - - Received disconnect from 192.168.1.85 port 60699:11: disconnected by user
<86>1 2023-02-17T15:05:17.329572-05:00 giganode1 sshd 2121176 - - Disconnected from user timp 192.168.1.85 port 60699
<86>1 2023-02-17T15:05:17.329642-05:00 giganode1 sshd 2121169 - - pam_unix(sshd:session): session closed for user timp
<30>1 2023-02-17T15:05:17.332535-05:00 giganode1 systemd 1 - - session-60.scope: Succeeded.
<38>1 2023-02-17T15:05:17.332911-05:00 giganode1 systemd-logind 1106 - - Session 60 logged out. Waiting for processes to exit.
<38>1 2023-02-17T15:05:17.334970-05:00 giganode1 systemd-logind 1106 - - Removed session 60.
<86>1 2023-02-17T15:05:26.262309-05:00 giganode1 sshd 2121232 - - Accepted password for testguy from 192.168.1.85 port 60700 ssh2
<30>1 2023-02-17T15:05:26.287269-05:00 giganode1 systemd 1 - - Created slice User Slice of UID 1001.
<30>1 2023-02-17T15:05:26.287513-05:00 giganode1 systemd 1 - - Starting User runtime directory /run/user/1001...
<38>1 2023-02-17T15:05:26.299549-05:00 giganode1 systemd-logind 1106 - - New session 61 of user testguy.
<30>1 2023-02-17T15:05:26.335628-05:00 giganode1 systemd 1 - - Started User runtime directory /run/user/1001.
<30>1 2023-02-17T15:05:26.360909-05:00 giganode1 systemd 1 - - Starting User Manager for UID 1001...
<86>1 2023-02-17T15:05:26.410190-05:00 giganode1 systemd 2121238 - - pam_unix(systemd-user:session): session opened for user testguy by (uid=0)
<30>1 2023-02-17T15:05:26.442129-05:00 giganode1 systemd 2121238 - - Started Mark boot as successful after the user session has run 2 minutes.
<30>1 2023-02-17T15:05:26.448283-05:00 giganode1 systemd 2121238 - - Starting D-Bus User Message Bus Socket.
<30>1 2023-02-17T15:05:26.450268-05:00 giganode1 systemd 2121238 - - Reached target Timers.
<30>1 2023-02-17T15:05:26.451644-05:00 giganode1 systemd 2121238 - - Reached target Paths.
<30>1 2023-02-17T15:05:26.451836-05:00 giganode1 systemd 2121238 - - Listening on D-Bus User Message Bus Socket.
<30>1 2023-02-17T15:05:26.451901-05:00 giganode1 systemd 2121238 - - Reached target Sockets.
<30>1 2023-02-17T15:05:26.452165-05:00 giganode1 systemd 2121238 - - Reached target Basic System.
<30>1 2023-02-17T15:05:26.452239-05:00 giganode1 systemd 2121238 - - Reached target Default.
<30>1 2023-02-17T15:05:26.452522-05:00 giganode1 systemd 2121238 - - Startup finished in 34ms.
<30>1 2023-02-17T15:05:26.452946-05:00 giganode1 systemd 1 - - Started User Manager for UID 1001.
<30>1 2023-02-17T15:05:26.456512-05:00 giganode1 systemd 1 - - Started Session 61 of user testguy.
<86>1 2023-02-17T15:05:26.498231-05:00 giganode1 sshd 2121232 - - pam_unix(sshd:session): session opened for user testguy by (uid=0)
<43>1 2023-02-17T15:05:31.460011-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<43>1 2023-02-17T15:06:01.500105-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<85>1 2023-02-17T15:06:10.514231-05:00 giganode1 sudo 2121357 - - pam_unix(sudo:auth): authentication failure; logname=testguy uid=1001 euid=0 tty=/dev/pts/1 ruser=testguy rhost=  user=testguy
<83>1 2023-02-17T15:06:18.276468-05:00 giganode1 sudo 2121357 - - pam_unix(sudo:auth): conversation failed
<82>1 2023-02-17T15:06:18.276723-05:00 giganode1 sudo 2121357 - - pam_unix(sudo:auth): auth could not identify password for [testguy]
<81>1 2023-02-17T15:06:20.337070-05:00 giganode1 sudo 2121357 - -  testguy : user NOT in sudoers ; TTY=pts/1 ; PWD=/home/testguy ; USER=root ; COMMAND=/bin/bash
<22>1 2023-02-17T15:06:20.360434-05:00 giganode1 sendmail 2121367 - - 31HK6Kvk2121367: from=testguy, size=262, class=0, nrcpts=1, msgid=<202302172006.31HK6Kvk2121367@giganode1.thepushors.com>, relay=testguy@localhost
<22>1 2023-02-17T15:06:20.392953-05:00 giganode1 sendmail 2121367 - - STARTTLS=client, relay=[127.0.0.1], version=TLSv1.3, verify=FAIL, cipher=TLS_AES_256_GCM_SHA384, bits=256/256
<22>1 2023-02-17T15:06:20.393273-05:00 giganode1 sendmail 2121368 - - STARTTLS=server, relay=localhost [127.0.0.1], version=TLSv1.3, verify=NOT, cipher=TLS_AES_256_GCM_SHA384, bits=256/256
<22>1 2023-02-17T15:06:20.491127-05:00 giganode1 sendmail 2121368 - - 31HK6KcH2121368: from=<testguy@giganode1.thepushors.com>, size=558, class=0, nrcpts=1, msgid=<202302172006.31HK6Kvk2121367@giganode1.thepushors.com>, proto=ESMTPS, daemon=MTA, relay=localhost [127.0.0.1]
<22>1 2023-02-17T15:06:20.492202-05:00 giganode1 sendmail 2121367 - - 31HK6Kvk2121367: to=root, ctladdr=testguy (1001/1002), delay=00:00:00, xdelay=00:00:00, mailer=relay, pri=30262, relay=[127.0.0.1] [127.0.0.1], dsn=2.0.0, stat=Sent (31HK6KcH2121368 Message accepted for delivery)
<22>1 2023-02-17T15:06:21.533268-05:00 giganode1 sendmail 2121369 - - 31HK6KcH2121368: to=<root@giganode1.thepushors.com>, ctladdr=<testguy@giganode1.thepushors.com> (1001/1002), delay=00:00:01, xdelay=00:00:01, mailer=local, pri=30846, dsn=2.0.0, stat=Sent
<85>1 2023-02-17T15:06:30.023699-05:00 giganode1 sudo 2121376 - -     timp : TTY=pts/0 ; PWD=/home/timp ; USER=root ; COMMAND=/bin/tail /var/log/messages
<87>1 2023-02-17T15:06:30.027500-05:00 giganode1 sudo 2121376 - - pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
<86>1 2023-02-17T15:06:30.027697-05:00 giganode1 sudo 2121376 - - pam_unix(sudo:session): session opened for user root by timp(uid=0)
<86>1 2023-02-17T15:06:30.028461-05:00 giganode1 sudo 2121376 - - pam_unix(sudo:session): session closed for user root
<43>1 2023-02-17T15:06:31.540303-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<85>1 2023-02-17T15:06:36.718095-05:00 giganode1 sudo 2121425 - -     timp : TTY=pts/0 ; PWD=/home/timp ; USER=root ; COMMAND=/bin/tail /var/log/secure
<87>1 2023-02-17T15:06:36.720706-05:00 giganode1 sudo 2121425 - - pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
<86>1 2023-02-17T15:06:36.720888-05:00 giganode1 sudo 2121425 - - pam_unix(sudo:session): session opened for user root by timp(uid=0)
<86>1 2023-02-17T15:06:36.722439-05:00 giganode1 sudo 2121425 - - pam_unix(sudo:session): session closed for user root
<43>1 2023-02-17T15:07:01.601769-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<43>1 2023-02-17T15:07:31.640785-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<30>1 2023-02-17T15:07:33.934788-05:00 giganode1 systemd 2121238 - - Starting Mark boot as successful...
<30>1 2023-02-17T15:07:33.957554-05:00 giganode1 systemd 2121238 - - Started Mark boot as successful.
<43>1 2023-02-17T15:08:01.680945-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<85>1 2023-02-17T15:08:06.177390-05:00 giganode1 sudo 2121517 - -     timp : TTY=pts/0 ; PWD=/home/timp ; USER=root ; COMMAND=/bin/tail -25 /var/log/secure
<87>1 2023-02-17T15:08:06.178457-05:00 giganode1 sudo 2121517 - - pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
<86>1 2023-02-17T15:08:06.178640-05:00 giganode1 sudo 2121517 - - pam_unix(sudo:session): session opened for user root by timp(uid=0)
<86>1 2023-02-17T15:08:06.181518-05:00 giganode1 sudo 2121517 - - pam_unix(sudo:session): session closed for user root
<43>1 2023-02-17T15:08:31.721314-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<43>1 2023-02-17T15:09:01.767649-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<43>1 2023-02-17T15:09:31.825862-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<85>1 2023-02-17T15:09:50.519966-05:00 giganode1 sudo 2121655 - -     timp : TTY=pts/0 ; PWD=/home/timp ; USER=root ; COMMAND=/bin/grep sudo /var/log/secure
<87>1 2023-02-17T15:09:50.521114-05:00 giganode1 sudo 2121655 - - pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
<86>1 2023-02-17T15:09:50.529896-05:00 giganode1 sudo 2121655 - - pam_unix(sudo:session): session opened for user root by timp(uid=0)
<86>1 2023-02-17T15:09:50.530198-05:00 giganode1 sudo 2121655 - - pam_unix(sudo:session): session closed for user root
<30>1 2023-02-17T15:10:00.131633-05:00 giganode1 systemd 1 - - Starting system activity accounting tool...
<30>1 2023-02-17T15:10:00.218347-05:00 giganode1 systemd 1 - - sysstat-collect.service: Succeeded.
<30>1 2023-02-17T15:10:00.218945-05:00 giganode1 systemd 1 - - Started system activity accounting tool.
<43>1 2023-02-17T15:10:01.931050-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<43>1 2023-02-17T15:10:32.035427-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<43>1 2023-02-17T15:11:02.132529-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<43>1 2023-02-17T15:11:32.249831-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<43>1 2023-02-17T15:12:02.355062-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<43>1 2023-02-17T15:12:32.383311-05:00 giganode1 rsyslogd 2018377 - - cannot connect to 192.168.1.85:5140: Connection refused [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2027 ]
<46>1 2023-02-17T15:13:02.423570-05:00 giganode1 rsyslogd 2018377 - - action 'action-7-builtin:omfwd' resumed (module 'builtin:omfwd') [v8.2102.0-10.el8 try https://www.rsyslog.com/e/2359 ]
